// Drawing the generated cover as a real object.
//
// One off-screen square, one full-screen triangle, one ray-marching pixel
// shader. The result is handed to Direct2D as an ordinary bitmap, which is
// also how video frames reach the canvas - so nothing has to interleave D3D
// and D2D inside a frame, and the rest of the interface knows nothing about
// any of this.
#include "pg.h"

#include "blob_vs.h"        // generated by fxc during the build
#include "blob_ps.h"

// Must match the cbuffer in blob.hlsl, 16-byte aligned.
struct BlobConstants {
    float time[4];          // t, pulse, level, unused
    float params[4];        // ball count, blend radius, seed, rotation speed
    float light[4];         // w intensity
    float lamp[3][4];       // the three lamps, rgb
    float bg0[4];
    float bg1[4];
    float ball[8][4];       // xyz centre, w radius
    float tint[8][4];
};

struct BlobRenderer::Impl {
    ComPtr<ID3D11Device>        dev;
    ComPtr<ID3D11DeviceContext> ctx;
    ComPtr<ID2D1DeviceContext>  d2d;
    ComPtr<ID3D11VertexShader>  vs;
    ComPtr<ID3D11PixelShader>   ps;
    ComPtr<ID3D11Buffer>        cb;
    ComPtr<ID3D11RasterizerState> rs;

    ComPtr<ID3D11Texture2D>     tex;
    ComPtr<ID3D11RenderTargetView> rtv;
    ComPtr<ID2D1Bitmap1>        bmp;
    int  size = 0;
    bool ok = false;
};

BlobRenderer::~BlobRenderer() { shutdown(); }

void BlobRenderer::shutdown() {
    delete p_;
    p_ = nullptr;
}

bool BlobRenderer::ready() const { return p_ && p_->ok; }

bool BlobRenderer::init(ID3D11Device* dev, ID3D11DeviceContext* ctx, ID2D1DeviceContext* d2d) {
    shutdown();
    if (!dev || !ctx || !d2d) return false;
    // The shader needs real loops, which feature level 9 cannot do. Anything
    // that old simply keeps the flat drawing.
    if (dev->GetFeatureLevel() < D3D_FEATURE_LEVEL_10_0) return false;

    auto* p = new Impl();
    p->dev = dev;
    p->ctx = ctx;
    p->d2d = d2d;

    if (FAILED(dev->CreateVertexShader(kBlobVS, sizeof(kBlobVS), nullptr, &p->vs)) ||
        FAILED(dev->CreatePixelShader(kBlobPS, sizeof(kBlobPS), nullptr, &p->ps))) {
        delete p;
        return false;
    }

    D3D11_BUFFER_DESC bd{};
    bd.ByteWidth = sizeof(BlobConstants);
    bd.Usage = D3D11_USAGE_DYNAMIC;
    bd.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    bd.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
    if (FAILED(dev->CreateBuffer(&bd, nullptr, &p->cb))) { delete p; return false; }

    D3D11_RASTERIZER_DESC rd{};
    rd.FillMode = D3D11_FILL_SOLID;
    rd.CullMode = D3D11_CULL_NONE;
    rd.DepthClipEnable = TRUE;
    dev->CreateRasterizerState(&rd, &p->rs);

    p->ok = true;
    p_ = p;
    return true;
}

// The off-screen square, rebuilt whenever the sleeve changes size.
static bool ensureTarget(BlobRenderer::Impl* p, int size) {
    if (p->tex && p->size == size) return true;
    p->bmp.Reset();
    p->rtv.Reset();
    p->tex.Reset();
    p->size = 0;

    D3D11_TEXTURE2D_DESC td{};
    td.Width = td.Height = (UINT)size;
    td.MipLevels = 1;
    td.ArraySize = 1;
    td.Format = DXGI_FORMAT_B8G8R8A8_UNORM;          // what Direct2D wants
    td.SampleDesc.Count = 1;
    td.Usage = D3D11_USAGE_DEFAULT;
    td.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
    if (FAILED(p->dev->CreateTexture2D(&td, nullptr, &p->tex))) return false;
    if (FAILED(p->dev->CreateRenderTargetView(p->tex.Get(), nullptr, &p->rtv))) return false;

    ComPtr<IDXGISurface> surf;
    if (FAILED(p->tex.As(&surf))) return false;
    D2D1_BITMAP_PROPERTIES1 bp = D2D1::BitmapProperties1(
        D2D1_BITMAP_OPTIONS_NONE,
        D2D1::PixelFormat(DXGI_FORMAT_B8G8R8A8_UNORM, D2D1_ALPHA_MODE_IGNORE), 96.f, 96.f);
    if (FAILED(p->d2d->CreateBitmapFromDxgiSurface(surf.Get(), &bp, &p->bmp))) return false;

    p->size = size;
    return true;
}

ID2D1Bitmap1* BlobRenderer::frame(const CoverPlan& plan, int size, float time,
                                  float pulse, float level) {
    if (!p_ || !p_->ok) return nullptr;
    size = clampi(size, 64, 640);
    if (!ensureTarget(p_, size)) return nullptr;

    BlobConstants c{};
    c.time[0] = time;
    c.time[1] = pulse;
    c.time[2] = level;

    int n = (int)std::min<size_t>(plan.lobes.size(), 8);
    c.params[0] = (float)n;
    // The beat does not only move the lobes, it melts them together: the blend
    // radius opens up on the kick, so the whole thing swells as one body.
    c.params[1] = 0.23f + 0.20f * pulse;
    c.params[2] = plan.spread * 37.0f;                // any stable per-track number
    c.params[3] = 0.32f + plan.rot * 0.9f;            // rotation speed and direction

    c.light[3] = 1.25f + 0.60f * level;

    // Three lamps in contrasting colours around the track's own hue. The body
    // is nearly colourless, so this is where all the colour comes from - and
    // contrast between the lamps is what keeps it from looking monochrome.
    static const float kOff[3] = { 0.f, 0.34f, -0.27f };
    static const float kLum[3] = { 0.60f, 0.52f, 0.50f };
    for (int k = 0; k < 3; ++k)
        coverHsl(plan.hue + kOff[k], 0.95f, kLum[k],
                 c.lamp[k][0], c.lamp[k][1], c.lamp[k][2]);

    // The backdrop keeps the track's own colours, just very dark.
    const CoverLobe& first = plan.lobes.empty() ? CoverLobe() : plan.lobes[0];
    c.bg0[0] = first.cr * 0.10f; c.bg0[1] = first.cg * 0.10f; c.bg0[2] = first.cb * 0.12f;
    c.bg1[0] = 0.012f; c.bg1[1] = 0.012f; c.bg1[2] = 0.018f;

    for (int i = 0; i < n; ++i) {
        const CoverLobe& b = plan.lobes[i];
        // The plan is laid out in the unit square; the object lives in a cube
        // around the origin, so the same numbers place it in three dimensions.
        float ph = b.phase + time * b.speed * 0.55f;
        float swell = 1.f + 0.30f * pulse * b.weight;
        float ox = (b.x - .5f) * 2.5f;
        float oy = (b.y - .5f) * 2.5f;
        float oz = b.z * 1.5f;
        c.ball[i][0] = (ox + b.dx * 2.2f * sinf(ph)) * swell;
        c.ball[i][1] = (oy + b.dy * 2.2f * cosf(ph * 0.83f)) * swell;
        c.ball[i][2] = oz * (1.f + 0.18f * sinf(ph * 0.7f));
        c.ball[i][3] = b.r * 0.92f * (0.85f + 0.35f * pulse * b.weight);
        c.tint[i][0] = b.cr;
        c.tint[i][1] = b.cg;
        c.tint[i][2] = b.cb;
    }

    D3D11_MAPPED_SUBRESOURCE m{};
    if (FAILED(p_->ctx->Map(p_->cb.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &m))) return nullptr;
    memcpy(m.pData, &c, sizeof(c));
    p_->ctx->Unmap(p_->cb.Get(), 0);

    ID3D11DeviceContext* ctx = p_->ctx.Get();
    ID3D11RenderTargetView* rtv = p_->rtv.Get();
    ctx->OMSetRenderTargets(1, &rtv, nullptr);
    D3D11_VIEWPORT vp{ 0.f, 0.f, (float)size, (float)size, 0.f, 1.f };
    ctx->RSSetViewports(1, &vp);
    if (p_->rs) ctx->RSSetState(p_->rs.Get());
    ctx->IASetInputLayout(nullptr);
    ctx->IASetVertexBuffers(0, 0, nullptr, nullptr, nullptr);
    ctx->IASetIndexBuffer(nullptr, DXGI_FORMAT_UNKNOWN, 0);
    ctx->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ctx->VSSetShader(p_->vs.Get(), nullptr, 0);
    ctx->PSSetShader(p_->ps.Get(), nullptr, 0);
    ID3D11Buffer* cb = p_->cb.Get();
    ctx->PSSetConstantBuffers(0, 1, &cb);
    ctx->GSSetShader(nullptr, nullptr, 0);
    ctx->HSSetShader(nullptr, nullptr, 0);
    ctx->DSSetShader(nullptr, nullptr, 0);
    ctx->OMSetBlendState(nullptr, nullptr, 0xFFFFFFFF);
    ctx->OMSetDepthStencilState(nullptr, 0);
    ctx->Draw(3, 0);

    // Direct2D is about to read this texture, so it must not still be bound
    // as a render target.
    ID3D11RenderTargetView* none = nullptr;
    ctx->OMSetRenderTargets(1, &none, nullptr);
    return p_->bmp.Get();
}
