// Interface language: Ukrainian (source), English, Russian.
//
// Strings are keyed by the Ukrainian original, so call sites stay readable and
// nothing has to be renumbered when a string is added. The lookup table is
// built once before any worker thread starts and is read-only afterwards, which
// makes T() safe to call from the decode threads for their error messages.
#include "pg.h"

std::atomic<int> g_lang{ LANG_UK };

namespace {

struct Tr { const wchar_t* uk; const wchar_t* en; const wchar_t* ru; };

const Tr kTable[] = {
// ---- command bar / menus -------------------------------------------------
{ L"Автопідгонка: вимкнена  (A)", L"Auto-fit: off  (A)", L"Автоподгонка: выключена  (A)" },
{ L"Автопідгонка: масштаб під вікно  (A)", L"Auto-fit: picture to window  (A)", L"Автоподгонка: масштаб под окно  (A)" },
{ L"Автопідгонка: вікно під зображення  (A)", L"Auto-fit: window to picture  (A)", L"Автоподгонка: окно под изображение  (A)" },
{ L"Автопідгонка: вимкнена", L"Auto-fit: off", L"Автоподгонка: выключена" },
{ L"Автопідгонка: під вікно", L"Auto-fit: to window", L"Автоподгонка: под окно" },
{ L"Автопідгонка: вікно під фото", L"Auto-fit: window to photo", L"Автоподгонка: окно под фото" },
{ L"Вписати у вікно", L"Fit to window", L"Вписать в окно" },
{ L"Масштаб 100%", L"Zoom 100%", L"Масштаб 100%" },
{ L"Обернути ліворуч", L"Rotate left", L"Повернуть влево" },
{ L"Обернути праворуч", L"Rotate right", L"Повернуть вправо" },
{ L"Дзеркально по горизонталі", L"Flip horizontally", L"Отразить по горизонтали" },
{ L"Дзеркально по вертикалі", L"Flip vertically", L"Отразить по вертикали" },
{ L"Сітка папки", L"Folder grid", L"Сетка папки" },
{ L"Стрічка кадрів", L"Filmstrip", L"Лента кадров" },
{ L"Відомості", L"Details", L"Сведения" },
{ L"Копіювати", L"Copy", L"Копировать" },
{ L"Показати в провіднику", L"Show in Explorer", L"Показать в проводнике" },
{ L"Відкрити нове вікно", L"Open a new window", L"Открыть новое окно" },
{ L"Поверх усіх вікон", L"Always on top", L"Поверх всех окон" },
{ L"Зробити шпалерами", L"Set as wallpaper", L"Сделать обоями" },
{ L"Перемістити в кошик", L"Move to Recycle Bin", L"Переместить в корзину" },
{ L"Налаштування", L"Settings", L"Настройки" },
{ L"Сітка папки  (G)", L"Folder grid  (G)", L"Сетка папки  (G)" },
{ L"Переглядач  (Esc)", L"Viewer  (Esc)", L"Просмотрщик  (Esc)" },
{ L"Відкрити файл  (Ctrl+O)", L"Open file  (Ctrl+O)", L"Открыть файл  (Ctrl+O)" },
{ L" зображень", L" images", L" изображений" },
{ L"Швидкий переглядач зображень", L"Fast image viewer", L"Быстрый просмотрщик изображений" },
{ L"Гарячі клавіші  (F1)", L"Keyboard shortcuts  (F1)", L"Горячие клавиши  (F1)" },
{ L"Налаштування  (Ctrl+,)", L"Settings  (Ctrl+,)", L"Настройки  (Ctrl+,)" },
{ L"Відкріпити  (P)", L"Unpin  (P)", L"Открепить  (P)" },
{ L"Поверх усіх вікон  (P)", L"Always on top  (P)", L"Поверх всех окон  (P)" },
{ L"Світла тема", L"Light theme", L"Светлая тема" },
{ L"Темна тема", L"Dark theme", L"Тёмная тема" },
{ L"Перетягніть зображення сюди", L"Drop an image here", L"Перетащите изображение сюда" },
{ L"Підтримується ", L"Supports ", L"Поддерживается " },
{ L" форматів", L" formats", L" форматов" },
{ L"Відкрити файл", L"Open file", L"Открыть файл" },
{ L"Відкрити папку", L"Open folder", L"Открыть папку" },
{ L"Не вдалося відкрити", L"Could not open", L"Не удалось открыть" },
{ L"Попереднє  (←)", L"Previous  (←)", L"Предыдущее  (←)" },
{ L"Наступне  (→)", L"Next  (→)", L"Следующее  (→)" },
{ L"Зменшити  (−)", L"Zoom out  (−)", L"Уменьшить  (−)" },
{ L"Вписати / 100%  (0 / 1)", L"Fit / 100%  (0 / 1)", L"Вписать / 100%  (0 / 1)" },
{ L"Збільшити  (+)", L"Zoom in  (+)", L"Увеличить  (+)" },
{ L"Вписати у вікно  (0)", L"Fit to window  (0)", L"Вписать в окно  (0)" },
{ L"Обернути ліворуч  (Shift+R)", L"Rotate left  (Shift+R)", L"Повернуть влево  (Shift+R)" },
{ L"Обернути праворуч  (R)", L"Rotate right  (R)", L"Повернуть вправо  (R)" },
{ L"Дзеркально по горизонталі  (H)", L"Flip horizontally  (H)", L"Отразить по горизонтали  (H)" },
{ L"Дзеркально по вертикалі  (V)", L"Flip vertically  (V)", L"Отразить по вертикали  (V)" },
{ L"Зупинити показ  (Space)", L"Stop slideshow  (Space)", L"Остановить показ  (Space)" },
{ L"Слайдшоу  (Space)", L"Slideshow  (Space)", L"Слайдшоу  (Space)" },
{ L"Вийти з повного екрана  (F11)", L"Exit full screen  (F11)", L"Выйти из полноэкранного  (F11)" },
{ L"На весь екран  (F11)", L"Full screen  (F11)", L"Во весь экран  (F11)" },
{ L"Стрічка кадрів  (T)", L"Filmstrip  (T)", L"Лента кадров  (T)" },
{ L"Відомості  (I)", L"Details  (I)", L"Сведения  (I)" },
{ L"Копіювати  (Ctrl+C)", L"Copy  (Ctrl+C)", L"Копировать  (Ctrl+C)" },
{ L"У кошик  (Del)", L"To Recycle Bin  (Del)", L"В корзину  (Del)" },
{ L"Більше", L"More", L"Ещё" },
{ L"Попередній файл  (PgUp)", L"Previous file  (PgUp)", L"Предыдущий файл  (PgUp)" },
{ L"−5 секунд  (←)", L"−5 seconds  (←)", L"−5 секунд  (←)" },
{ L"Пауза  (Space)", L"Pause  (Space)", L"Пауза  (Space)" },
{ L"Відтворити  (Space)", L"Play  (Space)", L"Воспроизвести  (Space)" },
{ L"+5 секунд  (→)", L"+5 seconds  (→)", L"+5 секунд  (→)" },
{ L"Наступний файл  (PgDn)", L"Next file  (PgDn)", L"Следующий файл  (PgDn)" },
{ L"Швидкість  (S)", L"Speed  (S)", L"Скорость  (S)" },
{ L"Увімкнути звук  (M)", L"Unmute  (M)", L"Включить звук  (M)" },
{ L"Вимкнути звук  (M)", L"Mute  (M)", L"Выключить звук  (M)" },
{ L"Закрити", L"Close", L"Закрыть" },

// ---- grid ----------------------------------------------------------------
{ L"Папку не вибрано", L"No folder selected", L"Папка не выбрана" },
{ L"За спаданням", L"Descending", L"По убыванию" },
{ L"За зростанням", L"Ascending", L"По возрастанию" },
{ L"Ім'я", L"Name", L"Имя" },
{ L"Дата", L"Date", L"Дата" },
{ L"Розмір", L"Size", L"Размер" },
{ L"Тип", L"Type", L"Тип" },
{ L"Сортування", L"Sorting", L"Сортировка" },
{ L"Менші мініатюри", L"Smaller thumbnails", L"Меньше миниатюры" },
{ L"Більші мініатюри", L"Larger thumbnails", L"Больше миниатюры" },
{ L"За іменем", L"By name", L"По имени" },
{ L"За датою", L"By date", L"По дате" },
{ L"За розміром", L"By size", L"По размеру" },
{ L"За типом", L"By type", L"По типу" },

// ---- details panel -------------------------------------------------------
{ L"Файл", L"File", L"Файл" },
{ L"Розмір у пікселях", L"Pixel size", L"Размер в пикселях" },
{ L"Тривалість", L"Duration", L"Длительность" },
{ L"Обсяг", L"File size", L"Объём" },
{ L"Змінено", L"Modified", L"Изменён" },
{ L"Немає даних", L"No data", L"Нет данных" },
{ L" Мп)", L" MP)", L" Мп)" },
{ L"Кадрів", L"Frames", L"Кадров" },
{ L"Камера", L"Camera", L"Камера" },
{ L"Об'єктив", L"Lens", L"Объектив" },
{ L"Знято", L"Taken", L"Снято" },
{ L"Експозиція", L"Exposure", L"Экспозиция" },
{ L"Софт", L"Software", L"Софт" },
{ L"декодовано за %.1f мс", L"decoded in %.1f ms", L"декодировано за %.1f мс" },

// ---- settings ------------------------------------------------------------
{ L"Вигляд", L"Appearance", L"Вид" },
{ L"Перегляд", L"Viewing", L"Просмотр" },
{ L"Відео", L"Video", L"Видео" },
{ L"Вікна", L"Windows", L"Окна" },
{ L"Формати", L"File types", L"Форматы" },
{ L"Мова", L"Language", L"Язык" },
{ L"Гарячі клавіші", L"Keyboard shortcuts", L"Горячие клавиши" },
{ L"Клавіша F1", L"Key F1", L"Клавиша F1" },
{ L"Показати", L"Show", L"Показать" },
{ L"Система", L"System", L"Система" },
{ L"Темна", L"Dark", L"Тёмная" },
{ L"Світла", L"Light", L"Светлая" },
{ L"Тема", L"Theme", L"Тема" },
{ L"Немає", L"None", L"Нет" },
{ L"Розмиття", L"Blur", L"Размытие" },
{ L"Задник вікна", L"Window backdrop", L"Задник окна" },
{ L"Що видно за фотографією", L"What shows behind the picture", L"Что видно за фотографией" },
{ L"Затемнення задника", L"Backdrop dimming", L"Затемнение задника" },
{ L"Накладається знизу, не зменшує фото", L"Overlays the bottom, never shrinks the picture", L"Накладывается снизу, не уменьшает фото" },
{ L"Вимкнено", L"Off", L"Выключено" },
{ L"Під вікно", L"To window", L"Под окно" },
{ L"Вікно під фото", L"Window to photo", L"Окно под фото" },
{ L"Автопідгонка", L"Auto-fit", L"Автоподгонка" },
{ L"Клавіша A", L"Key A", L"Клавиша A" },
{ L"Масштаб", L"Zoom", L"Масштаб" },
{ L"Гортання", L"Browse", L"Пролистывание" },
{ L"Колесо миші", L"Mouse wheel", L"Колесо мыши" },
{ L"Запам'ятовувати масштаб", L"Remember zoom", L"Запоминать масштаб" },
{ L"Для кожного файлу окремо", L"Separately for every file", L"Для каждого файла отдельно" },
{ L"Згладжування при збільшенні", L"Smoothing when zoomed in", L"Сглаживание при увеличении" },
{ L"Гортати папку по колу", L"Wrap around the folder", L"Листать папку по кругу" },
{ L"Інтервал слайдшоу", L"Slideshow interval", L"Интервал слайдшоу" },
{ L"Починати відтворення одразу", L"Start playback immediately", L"Начинать воспроизведение сразу" },
{ L"Продовжувати з місця зупинки", L"Resume where you left off", L"Продолжать с места остановки" },
{ L"Окремо для кожного відео", L"Separately for every video", L"Отдельно для каждого видео" },
{ L"Гучність", L"Volume", L"Громкость" },
{ L"Гучність ", L"Volume ", L"Громкость " },
{ L"Кожен файл у власному вікні", L"Every file in its own window", L"Каждый файл в своём окне" },
{ L"Інакше файли відкриваються в цьому ж вікні (швидше)", L"Otherwise files open in this window (faster)", L"Иначе файлы открываются в этом же окне (быстрее)" },
{ L"Клавіша P", L"Key P", L"Клавиша P" },
{ L"Відкрити ще одне вікно", L"Open one more window", L"Открыть ещё одно окно" },
{ L"Нове вікно", L"New window", L"Новое окно" },
{ L"Приховувати панелі", L"Hide the bars after", L"Прятать панели" },
{ L"Час бездіяльності до зникання", L"Idle time before they fade out", L"Время бездействия до исчезновения" },
{ L"Не ховати", L"Never", L"Не прятать" },
// ---- compressor ----------------------------------------------------------
{ L"Стиснути та конвертувати", L"Compress and convert", L"Сжать и конвертировать" },
{ L"Стиснути можна лише зображення", L"Only images can be compressed", L"Сжимать можно только изображения" },
{ L"Немає доступних кодувальників", L"No encoders are available", L"Нет доступных кодировщиков" },
{ L" (стиснуто)", L" (compressed)", L" (сжато)" },
{ L"Збереження…", L"Saving…", L"Сохранение…" },
{ L"Обробка папки…", L"Processing the folder…", L"Обработка папки…" },
{ L"У папці немає зображень", L"The folder has no images", L"В папке нет изображений" },
{ L"Збережено файлів: ", L"Files saved: ", L"Сохранено файлов: " },
{ L"Збережено: ", L"Saved: ", L"Сохранено: " },
{ L"Не вдалося зберегти", L"Could not save", L"Не удалось сохранить" },
{ L"Не вдалося закодувати", L"Could not encode", L"Не удалось закодировать" },
{ L"Не вдалося записати файл", L"Could not write the file", L"Не удалось записать файл" },
{ L"Закрити  (Esc)", L"Close  (Esc)", L"Закрыть  (Esc)" },
{ L"Оригінал", L"Original", L"Оригинал" },
{ L"Затисніть для оригіналу", L"Hold to see the original", L"Зажмите, чтобы увидеть оригинал" },
{ L"Формат", L"Format", L"Формат" },
{ L"Режим", L"Mode", L"Режим" },
{ L"Якість", L"Quality", L"Качество" },
{ L"Відсоток", L"Percent", L"Процент" },
{ L"Розмір файлу", L"File size", L"Размер файла" },
{ L"Формат без втрат — якість не регулюється", L"Lossless format - no quality to set", L"Формат без потерь - качество не регулируется" },
{ L"Частка від оригіналу", L"Share of the original", L"Доля от оригинала" },
{ L"Цільовий розмір", L"Target size", L"Целевой размер" },
{ L"Роздільність", L"Resolution", L"Разрешение" },
{ L"Зменшувати за потреби", L"Shrink if needed", L"Уменьшать при необходимости" },
{ L"Було", L"Before", L"Было" },
{ L"Стане", L"After", L"Станет" },
{ L"Різниця", L"Change", L"Разница" },
{ L"Підібрана якість", L"Quality picked", L"Подобранное качество" },
{ L"Менше зробити не вдалося", L"This is as small as it goes", L"Меньше сделать не удалось" },
{ L"Зберегти", L"Save", L"Сохранить" },
{ L"Зберегти як…", L"Save as…", L"Сохранить как…" },
{ L"Уся папка…", L"Whole folder…", L"Вся папка…" },
{ L"Обробити всі зображення папки в іншу теку", L"Process every image in the folder into another folder", L"Обработать все изображения папки в другую папку" },
{ L"Скасувати", L"Cancel", L"Отмена" },
{ L"Обрізати", L"Crop", L"Обрезать" },
{ L"Вільно", L"Free", L"Свободно" },
{ L"Поміняти сторони місцями", L"Swap the sides", L"Поменять стороны местами" },
{ L"Скинути обрізання", L"Reset the crop", L"Сбросить обрезку" },
{ L"Обрізати можна лише зображення", L"Only images can be cropped", L"Обрезать можно только изображения" },
{ L"Одразу", L"At once", L"Сразу" },
{ L"Позначені формати з'являться в меню «Відкрити за допомогою».", L"Checked types appear in the \"Open with\" menu.", L"Отмеченные форматы появятся в меню «Открыть с помощью»." },
{ L"Позначте формати й натисніть «Застосувати».", L"Check the types you want, then press Apply.", L"Отметьте форматы и нажмите «Применить»." },
{ L"Windows 11 не дозволяє програмі самій стати стандартною.", L"Windows 11 never lets an app make itself the default.", L"Windows 11 не позволяет программе самой стать стандартной." },
{ L"Далі натисніть «Зробити стандартною» і підтвердіть вибір у Windows.", L"Press \"Make default\" next and confirm the choice in Windows.", L"Далее нажмите «Сделать стандартной» и подтвердите выбор в Windows." },
{ L"Зробити стандартною", L"Make default", L"Сделать стандартной" },
{ L". Підтвердіть у Windows", L". Confirm in Windows", L". Подтвердите в Windows" },
{ L"Швидкий переглядач зображень і відео", L"Fast image and video viewer", L"Быстрый просмотрщик изображений и видео" },
{ L"Швидкість  (S / Ctrl+Shift+колесо)", L"Speed  (S / Ctrl+Shift+wheel)", L"Скорость  (S / Ctrl+Shift+колесо)" },
{ L"Найпоширеніші", L"Most common", L"Самые распространённые" },
{ L"Позначити всі", L"Check all", L"Отметить все" },
{ L"Решта", L"The rest", L"Остальные" },
{ L"Застосувати", L"Apply", L"Применить" },
{ L"Зняти все", L"Clear all", L"Снять все" },
{ L"Стандартні програми", L"Default apps", L"Приложения по умолчанию" },

// ---- shortcut sheets -----------------------------------------------------
{ L"Гарячі клавіші", L"Keyboard shortcuts", L"Горячие клавиши" },
{ L"Клавіші відео", L"Video keys", L"Клавиши видео" },
{ L"Space  /  клік", L"Space  /  click", L"Space  /  клик" },
{ L"Відтворити / пауза", L"Play / pause", L"Воспроизвести / пауза" },
{ L"Перемотати −5 / +5 секунд", L"Skip −5 / +5 seconds", L"Перемотать −5 / +5 секунд" },
{ L"Перемотати −30 / +30 секунд", L"Skip −30 / +30 seconds", L"Перемотать −30 / +30 секунд" },
{ L"Вимкнути / увімкнути звук", L"Mute / unmute", L"Выключить / включить звук" },
{ L"Швидкість відтворення", L"Playback speed", L"Скорость воспроизведения" },
{ L"Автопідгонка вікна та масштабу", L"Window and zoom auto-fit", L"Автоподгонка окна и масштаба" },
{ L"Попередній / наступний файл", L"Previous / next file", L"Предыдущий / следующий файл" },
{ L"Подвійний клік", L"Double click", L"Двойной клик" },
{ L"Повний екран", L"Full screen", L"Полный экран" },
{ L"Сітка папки / вихід", L"Folder grid / exit", L"Сетка папки / выход" },
{ L"Панель відомостей", L"Details panel", L"Панель сведений" },
{ L"Ця довідка", L"This help", L"Эта справка" },
{ L"Попереднє / наступне зображення", L"Previous / next image", L"Предыдущее / следующее изображение" },
{ L"Перше / останнє", L"First / last", L"Первое / последнее" },
{ L"+  −  /  Ctrl+Колесо", L"+  −  /  Ctrl+Wheel", L"+  −  /  Ctrl+Колесо" },
{ L"Збільшити / зменшити", L"Zoom in / out", L"Увеличить / уменьшить" },
{ L"Вписати у вікно / масштаб 100%", L"Fit to window / zoom 100%", L"Вписать в окно / масштаб 100%" },
{ L"Колесо", L"Wheel", L"Колесо" },
{ L"Масштаб (або гортання — див. W)", L"Zoom (or browse — see W)", L"Масштаб (или пролистывание — см. W)" },
{ L"Змінити дію колеса", L"Change what the wheel does", L"Изменить действие колеса" },
{ L"Автопідгонка: вимк / під вікно / вікно під фото", L"Auto-fit: off / to window / window to photo", L"Автоподгонка: выкл / под окно / окно под фото" },
{ L"Перетягування", L"Drag", L"Перетаскивание" },
{ L"Панорамування", L"Panning", L"Панорамирование" },
{ L"Вписати / 100%", L"Fit / 100%", L"Вписать / 100%" },
{ L"Слайдшоу", L"Slideshow", L"Слайдшоу" },
{ L"Обернути праворуч / ліворуч", L"Rotate right / left", L"Повернуть вправо / влево" },
{ L"Дзеркально по горизонталі / вертикалі", L"Flip horizontally / vertically", L"Отразить по горизонтали / вертикали" },
{ L"Копіювати зображення", L"Copy the image", L"Копировать изображение" },
{ L"Закріпити поверх усіх вікон", L"Pin on top of all windows", L"Закрепить поверх всех окон" },
{ L"Нове вікно / налаштування", L"New window / settings", L"Новое окно / настройки" },

// ---- messages ------------------------------------------------------------
{ L"Media Foundation недоступна", L"Media Foundation is unavailable", L"Media Foundation недоступна" },
{ L"Не вдалося відкрити відео", L"Could not open the video", L"Не удалось открыть видео" },
{ L"Останнє зображення", L"Last image", L"Последнее изображение" },
{ L"Перше зображення", L"First image", L"Первое изображение" },
{ L"Файл не знайдено", L"File not found", L"Файл не найден" },
{ L"Встановлено як шпалери", L"Set as wallpaper", L"Установлено как обои" },
{ L"Не вдалося встановити шпалери", L"Could not set the wallpaper", L"Не удалось установить обои" },
{ L"Не вдалося скопіювати", L"Could not copy", L"Не удалось скопировать" },
{ L"Скопійовано в буфер обміну", L"Copied to the clipboard", L"Скопировано в буфер обмена" },
{ L"Не вдалося видалити", L"Could not delete", L"Не удалось удалить" },
{ L"Переміщено в кошик", L"Moved to the Recycle Bin", L"Перемещено в корзину" },
{ L"Автопідгонка вимкнена  ·  100%", L"Auto-fit off  ·  100%", L"Автоподгонка выключена  ·  100%" },
{ L"Масштаб під вікно", L"Picture to window", L"Масштаб под окно" },
{ L"Вікно під зображення", L"Window to picture", L"Окно под изображение" },
{ L"Швидкість %.2gx", L"Speed %.2gx", L"Скорость %.2gx" },
{ L"Слайдшоу увімкнено", L"Slideshow on", L"Слайдшоу включено" },
{ L"Слайдшоу вимкнено", L"Slideshow off", L"Слайдшоу выключено" },
{ L"Вікно закріплено поверх інших", L"Window pinned on top", L"Окно закреплено поверх других" },
{ L"Закріплення знято", L"Unpinned", L"Закрепление снято" },
{ L"Зареєстровано форматів: ", L"Types registered: ", L"Зарегистрировано форматов: " },
{ L"Реєстрацію прибрано", L"Registration removed", L"Регистрация убрана" },
{ L"Не вдалося записати в реєстр", L"Could not write to the registry", L"Не удалось записать в реестр" },
{ L"Звук вимкнено", L"Muted", L"Звук выключен" },
{ L"Звук увімкнено", L"Unmuted", L"Звук включён" },
{ L"Колесо: гортання", L"Wheel: browse", L"Колесо: пролистывание" },
{ L"Колесо: масштаб", L"Wheel: zoom", L"Колесо: масштаб" },
{ L"Продовжено з ", L"Resumed from ", L"Продолжено с " },
{ L"Не вдалося ініціалізувати Direct3D / Direct2D.", L"Could not initialise Direct3D / Direct2D.", L"Не удалось инициализировать Direct3D / Direct2D." },
{ L"Зображення|", L"Images|", L"Изображения|" },
{ L"|Усі файли|*.*|", L"|All files|*.*|", L"|Все файлы|*.*|" },
{ L"Не вдалося прочитати файл", L"Could not read the file", L"Не удалось прочитать файл" },
{ L"Формат не підтримується або файл пошкоджено", L"Unsupported format or damaged file", L"Формат не поддерживается или файл повреждён" },
{ L"Не вдалося створити медіарушій", L"Could not create the media engine", L"Не удалось создать медиадвижок" },
{ L"Формат або кодек не підтримується системою", L"The system has no codec for this file", L"Формат или кодек не поддерживается системой" },
{ L"Помилка декодування", L"Decoding error", L"Ошибка декодирования" },
{ L"Помилка читання файлу", L"File read error", L"Ошибка чтения файла" },
{ L"Відтворення перервано", L"Playback aborted", L"Воспроизведение прервано" },
{ L"Не вдалося відтворити", L"Could not play", L"Не удалось воспроизвести" },

// ---- media properties ----------------------------------------------------
{ L"%.1f Мбіт/с", L"%.1f Mbit/s", L"%.1f Мбит/с" },
{ L"%u кбіт/с", L"%u kbit/s", L"%u кбит/с" },
{ L" біт/с", L" bit/s", L" бит/с" },
{ L"Відеокодек", L"Video codec", L"Видеокодек" },
{ L"%.0f кадр/с", L"%.0f fps", L"%.0f кадр/с" },
{ L"%.2f кадр/с", L"%.2f fps", L"%.2f кадр/с" },
{ L"Частота кадрів", L"Frame rate", L"Частота кадров" },
{ L"Бітрейт відео", L"Video bitrate", L"Битрейт видео" },
{ L"Аудіокодек", L"Audio codec", L"Аудиокодек" },
{ L"  (моно)", L"  (mono)", L"  (моно)" },
{ L"  (стерео)", L"  (stereo)", L"  (стерео)" },
{ L"Канали", L"Channels", L"Каналы" },
{ L"%.1f кГц", L"%.1f kHz", L"%.1f кГц" },
{ L"Частота", L"Sample rate", L"Частота" },
{ L"Бітрейт аудіо", L"Audio bitrate", L"Битрейт аудио" },

// ---- units ---------------------------------------------------------------
{ L"Б", L"B", L"Б" },
{ L"КБ", L"KB", L"КБ" },
{ L"МБ", L"MB", L"МБ" },
{ L"ГБ", L"GB", L"ГБ" },
{ L"ТБ", L"TB", L"ТБ" },
{ L"%.0f с", L"%.0f s", L"%.0f с" },
{ L"%.1f с", L"%.1f s", L"%.1f с" },
};

std::unordered_map<wstring, const Tr*>* g_index = nullptr;

} // namespace

void langInit() {
    if (g_index) return;
    g_index = new std::unordered_map<wstring, const Tr*>();
    g_index->reserve(sizeof(kTable) / sizeof(kTable[0]) * 2);
    for (const auto& t : kTable) (*g_index)[t.uk] = &t;
}

const wchar_t* T(const wchar_t* uk) {
    int lang = g_lang.load(std::memory_order_relaxed);
    if (lang == LANG_UK || !uk || !g_index) return uk;
    auto it = g_index->find(uk);
    if (it == g_index->end()) return uk;          // untranslated: show the original
    const wchar_t* v = (lang == LANG_EN) ? it->second->en : it->second->ru;
    return (v && *v) ? v : uk;
}
